<a href="https://colab.research.google.com/github/JSJeong-me/KOSA-Big-Data_Vision/blob/main/ML/0_Machine_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# from numpy import exp, array, random, dot

In [1]:
import numpy as np

In [2]:
training_set_inputs = np.array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1]])

In [6]:
training_set_inputs

array([[0, 0, 1],
       [1, 1, 1],
       [1, 0, 1],
       [0, 1, 1]])

In [3]:
training_set_outputs = np.array([0, 1, 1, 0]).reshape(-1,1)
#training_set_outputs = array([[0, 1, 1, 0]]).T

In [4]:
training_set_outputs

array([[0],
       [1],
       [1],
       [0]])

In [8]:
training_set_outputs.shape

(4, 1)

In [ ]:
training_set_outputs

In [ ]:
training_set_outputs.shape

In [ ]:
training_set_inputs.shape

In [9]:
np.random.seed(1)
synaptic_weights = 2 * np.random.random((3, 1)) - 1

for iteration in range(10000):
    output = 1 / (1 + np.exp(-(np.dot(training_set_inputs, synaptic_weights))))
    synaptic_weights += np.dot(training_set_inputs.T, (training_set_outputs - output) * output * (1 - output))

In [12]:
synaptic_weights

array([[ 9.67299303],
       [-0.2078435 ],
       [-4.62963669]])

In [17]:
print (1 / (1 + np.exp(-(np.dot(np.array([0, 1, 0]), synaptic_weights)))))

[0.44822538]
