<a href="https://colab.research.google.com/github/JSJeong-me/KOSA-Big-Data_Vision/blob/main/teachable-machine02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pwd

/content


In [2]:
!ls -l

total 7412
-rw-r--r-- 1 root root 7563542 Oct 12 07:11 converted_savedmodel.zip
drwxr-xr-x 2 root root    4096 Oct 12 07:20 cup
drwxr-xr-x 2 root root    4096 Oct 12 07:21 eraser
-rw-r--r-- 1 root root      36 Oct 12 06:53 labels.txt
drwxr-xr-x 4 root root    4096 Oct 12 06:53 model.savedmodel
drwxr-xr-x 2 root root    4096 Oct 12 07:17 remote
drwxr-xr-x 1 root root    4096 Oct  8 13:45 sample_data


In [3]:
!mkdir ./remote

mkdir: cannot create directory ‘./remote’: File exists


In [4]:
!mv ./지우게-samples.zip ./eraser

mv: cannot stat './지우게-samples.zip': No such file or directory


In [5]:
%cd ../eraser/

[Errno 2] No such file or directory: '../eraser/'
/content


In [6]:
!unzip ./지우게-samples.zip

unzip:  cannot find or open ./지우게-samples.zip, ./지우게-samples.zip.zip or ./지우게-samples.zip.ZIP.


In [7]:
!mv ./*.jpg ./remote/

mv: cannot stat './*.jpg': No such file or directory


In [8]:
!mkdir ./eraser

mkdir: cannot create directory ‘./eraser’: File exists


In [9]:
!mkdir ./cup

mkdir: cannot create directory ‘./cup’: File exists


In [10]:
!unzip ./리모컨-samples.zip

unzip:  cannot find or open ./리모컨-samples.zip, ./리모컨-samples.zip.zip or ./리모컨-samples.zip.ZIP.


In [11]:
!ls -l

total 7412
-rw-r--r-- 1 root root 7563542 Oct 12 07:11 converted_savedmodel.zip
drwxr-xr-x 2 root root    4096 Oct 12 07:20 cup
drwxr-xr-x 2 root root    4096 Oct 12 07:21 eraser
-rw-r--r-- 1 root root      36 Oct 12 06:53 labels.txt
drwxr-xr-x 4 root root    4096 Oct 12 06:53 model.savedmodel
drwxr-xr-x 2 root root    4096 Oct 12 07:17 remote
drwxr-xr-x 1 root root    4096 Oct  8 13:45 sample_data


In [12]:
!pwd

/content


In [13]:
%cd /content/

/content


In [14]:
from keras.models import load_model
from PIL import Image, ImageOps
import numpy as np

In [15]:
# Load the model
model = load_model('./model.savedmodel')

In [16]:
model.summary()

Model: "sequential_40"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
sequential_37 (Sequential)   (None, 1280)              410208    
_________________________________________________________________
sequential_39 (Sequential)   (None, 3)                 128400    
Total params: 538,608
Trainable params: 524,528
Non-trainable params: 14,080
_________________________________________________________________


In [17]:
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

In [18]:
!pwd

/content


In [19]:
image = Image.open('./remote/150.jpg')

In [20]:
size = (224, 224)
image = ImageOps.fit(image, size, Image.ANTIALIAS)

In [21]:
image_array = np.asarray(image)

In [22]:
image_array.shape

(224, 224, 3)

In [23]:
image_array[:10, :10, 0]  # Red

array([[107, 107, 107, 106, 106, 106, 108, 109, 107, 107],
       [107, 107, 107, 106, 106, 107, 108, 109, 108, 108],
       [107, 107, 108, 107, 107, 107, 108, 109, 108, 108],
       [107, 108, 108, 108, 108, 108, 109, 110, 109, 109],
       [107, 108, 109, 109, 109, 109, 109, 110, 109, 109],
       [107, 108, 109, 110, 109, 109, 109, 109, 110, 109],
       [107, 108, 109, 110, 109, 109, 109, 109, 110, 109],
       [107, 108, 109, 110, 110, 109, 109, 109, 110, 109],
       [109, 109, 109, 109, 109, 109, 109, 109, 109, 110],
       [109, 109, 109, 109, 109, 109, 109, 109, 111, 111]], dtype=uint8)

In [24]:
image_array[:10, :10, 1] #Green

array([[108, 108, 108, 107, 107, 107, 108, 109, 107, 107],
       [108, 108, 108, 107, 107, 107, 108, 109, 108, 108],
       [108, 108, 109, 108, 108, 107, 108, 109, 108, 108],
       [108, 109, 109, 109, 108, 108, 109, 110, 109, 109],
       [108, 109, 110, 110, 109, 109, 109, 110, 109, 109],
       [108, 108, 109, 110, 109, 109, 109, 109, 110, 109],
       [107, 108, 109, 110, 109, 109, 109, 109, 110, 109],
       [107, 108, 109, 110, 110, 109, 109, 109, 110, 109],
       [109, 109, 109, 109, 109, 109, 109, 109, 109, 110],
       [109, 109, 109, 109, 109, 109, 109, 109, 111, 111]], dtype=uint8)

In [25]:
#normalized_image_array[:10, :10, 2] # Blue

In [26]:
normalized_image_array = (image_array.astype(np.float32) / 127.0) - 1

In [27]:
data[0] = normalized_image_array

In [28]:
prediction = model.predict(data)


In [29]:
prediction

array([[1.0000000e+00, 6.0258310e-14, 1.6075816e-16]], dtype=float32)

In [30]:
print(prediction)

[[1.0000000e+00 6.0258310e-14 1.6075816e-16]]


In [31]:
prediction.max()

1.0

In [32]:




# Create the array of the right shape to feed into the keras model
# The 'length' or number of images you can put into the array is
# determined by the first position in the shape tuple, in this case 1.

# Replace this with the path to your image

#resize the image to a 224x224 with the same strategy as in TM2:
#resizing the image to be at least 224x224 and then cropping from the center


#turn the image into a numpy array

# Normalize the image

# Load the image into the array
data[0] = normalized_image_array

# run the inference
prediction = model.predict(data)
print(prediction)


[[1.0000000e+00 6.0258310e-14 1.6075816e-16]]
